const data = [
  {
    id: 1,
    image: process.env.PUBLIC_URL + `/images/bison.jpg`,
    name: "number1",
    backgroundColor: "red",
    cardFront: "Pick Me!",
    alt: "",
  },
  {
    id: 2,
    image: process.env.PUBLIC_URL + `/images/clownfish.jpg`,
    name: "number2",
    backgroundColor: "blue",
    cardFront: "Pick Me!",
    alt: "",
  },
  {
    id: 3,
    image: process.env.PUBLIC_URL + `/images/jaguar.jpg`,
    name: "Marley",
    backgroundColor: "red",
    cardFront: "Pick Me!",
    alt: "",
  },
  {
    id: 4,
    image: process.env.PUBLIC_URL + `/images/killerwhale.jpg`,
    name: "Whale",
    backgroundColor: "yellow",
    alt: "",
    cardFront: "Pick Me!",
  },
  {
    id: 5,
    image: process.env.PUBLIC_URL + `/images/koala.jpg`,
    name: "number5",
    backgroundColor: "violet",
    cardFront: "Pick Me!",
    alt: "",
  },
  {
    id: 6,
    image: process.env.PUBLIC_URL + `/images/monarchbutterfly.jpg`,
    name: "Butterfly",
    backgroundColor: "green",
    cardFront: "Pick Me!",
    alt: "",
  },
  {
    id: 7,
    image: process.env.PUBLIC_URL + `/images/panda.jpg`,
    name: "Panda",
    backgroundColor: "aqua",
    cardFront: "Pick Me!",
    alt: "",
  },
  {
    id: 8,
    image: process.env.PUBLIC_URL + `/images/plover.jpg`,
    name: "Plover",
    backgroundColor: "grey",
    cardFront: "Pick Me!",
    alt: "",
  },
  {
    id: 9,
    image: process.env.PUBLIC_URL + `/images/polarBear.jpg`,
    name: "Polar Bear",
    cardFront: "Pick Me!",
    alt: "",
  },
  {
    id: 10,
    image: process.env.PUBLIC_URL + `/images/seaTurtle.jpg`,
    name: "Sea Turtke",
    cardFront: "Pick Me!",
    alt: "",
  },
  {
    id: 11,
    image: process.env.PUBLIC_URL + `/images/tiger.jpg`,
    name: "Tiger",
    cardFront: "Pick Me!",
    alt: "",
  },
  {
    id: 12,
    image: process.env.PUBLIC_URL + `/images/toucan.jpg`,
    name: "Toucan",
    cardFront: "Pick Me!",
    alt: "",
  },
];
export default data;
