const data = [
  {
    id: 1,
    image: process.env.PUBLIC_URL + `/images/bison.jpg`,
    characterName: "number1",
    backgroundColor: "red",
    alt: "",
  },
  {
    id: 2,
    image: process.env.PUBLIC_URL + `/images/clownfish.jpg`,
    characterName: "number2",
    backgroundColor: "blue",
    alt: "",
  },
  {
    id: 3,
    image: process.env.PUBLIC_URL + `/images/jaguar.jpg`,
    characterName: "number3",
    backgroundColor: "red",
    alt: "",
  },
  {
    id: 4,
    image: process.env.PUBLIC_URL + `/images/killerwhale.jpg`,
    characterName: "number4",
    backgroundColor: "yellow",
    alt: "",
  },
  {
    id: 5,
    image: process.env.PUBLIC_URL + `/images/koala.jpg`,
    characterName: "number5",
    backgroundColor: "violet",
    alt: "",
  },
  {
    id: 6,
    image: process.env.PUBLIC_URL + `/images/monarchbutterfly.jpg`,
    characterName: "number6",
    backgroundColor: "green",
    alt: "",
  },
  {
    id: 7,
    image: process.env.PUBLIC_URL + `/images/panda.jpg`,
    characterName: "number7",
    backgroundColor: "aqua",
    alt: "",
  },
  {
    id: 8,
    image: process.env.PUBLIC_URL + `/images/plover.jpg`,
    characterName: "number8",
    backgroundColor: "grey",
    alt: "",
  },
  {
    id: 9,
    image: process.env.PUBLIC_URL + `/images/polarBear.jpg`,
    characterName: "number9",
    alt: "",
  },
  {
    id: 10,
    image: process.env.PUBLIC_URL + `/images/seaTurtle.jpg`,
    characterName: "number10",
    alt: "",
  },
  {
    id: 11,
    image: process.env.PUBLIC_URL + `/images/tiger.jpg`,
    characterName: "number11",
    alt: "",
  },
  {
    id: 12,
    image: process.env.PUBLIC_URL + `/images/toucan.jpg`,
    characterName: "number12",
    alt: "",
  },
];
export default data;
